# Site settings
title: TeenyGenie
email: teeny@teeny-genie.com
description: > # this means to ignore newlines until "baseurl:"
  Our genie pants are the bee's knees for little legs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://teeny-genie.com" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
